version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  app:
    depends_on:
      - 'postgres'      
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails_admin'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box


volumes:
  postgres:
  box: